//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databaseexample
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class login
    {
       
        public int id { get; set; }
        [Required(ErrorMessage ="UserName Required")]
        public string Usern { get; set; }
        [Required(ErrorMessage ="Password Required")]
        public string password { get; set; }
        [Required(ErrorMessage ="Role Required")]
        public string role { get; set; }
    }
}
