//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase
    {
        public int Pid { get; set; }
        public string Pname { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> Pprice { get; set; }
        public Nullable<int> Sprice { get; set; }
        public Nullable<System.DateTime> dateofP { get; set; }
    }
}
