//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictureUploading
{
    using System;
    using System.Collections.Generic;
    
    public partial class pictable
    {
        public int id { get; set; }
        public string picpath { get; set; }
        public string picname { get; set; }
    }
}
